
on: pull_request
name: CI
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project PhotoGallery.xcodeproj -scheme PhotoGallery -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' build test
