
on: pull_request
name: CI
jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: |
       xcrun simctl list
       xcodebuild clean test -project PhotoGallery.xcodeproj -scheme PhotoGallery -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
          
