
on: pull_request
name: CI
jobs:
  
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild build
      run: |
       xcodebuild clean -project PhotoGallery.xcodeproj -scheme PhotoGallery -sdk iphonesimulator build
          
    test:
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: |
       xcodebuild clean build test -project "PhotoGallery.xcodeproj" -scheme "PhotoGallery" -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
