
on: pull_request
name: CI
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Testing
        run: |
          ls
          xcodebuild -scheme PhotoGallery test
          
