
on: pull_request
name: CI
jobs:
  test:

  runs-on: macOS-latest

steps:
- uses: actions/checkout@v2
- name: Force Xcode 11
  run: sudo xcode-select -switch /Applications/Xcode_11.3.app
- name: List Simulators
  run: xcrun instruments -s
- name: Run tests
  run: xcodebuild clean test -workspace 'PhotoGallery.xcworkspace' -scheme 'PhotoGallery' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
