
on: pull_request
name: CI
jobs:
  
  build_test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: |
       xcodebuild clean test -project "PhotoGallery.xcodeproj" -scheme "PhotoGallery" -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
