
on: pull_request
name: CI
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: |
            xcodebuild

  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Testing
        run: |
          ls
          xcodebuild -scheme PhotoGallery -destination 'platform=iOS Simulator,name=iPhone 8' test
          
